name: Here is my static web project
pageTitle: What I'm up to
url: https://altertek.org/en/
logo: static/img/logo.jpg
favicon: static/img/logo.jpg
bio: Welcome everyone on our Web PaaS Power - OVHcloud
