# Generated by Django 3.1.2 on 2020-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='next_question',
            field=models.IntegerField(default=0),
        ),
    ]
