# This is a basic workflow to help you get started with Actions
name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # pull_request:
    # branches: [ master ]
# Triggers for every push
# on: [push]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # # This workflow contains a single job called "build"
  # build:
  # This workflow contains a single job called "build"
  deploy:    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: pitscher/ovh-deploy-hosting-action@v1
      
        # Deploys your repository to the following environment
        env:
          OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
          OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
          OVH_HOSTING_DOMAIN: ssh.cluster022.hosting.ovh.net
          REPOSITORY_NAME: managey
          REPOSITORY_URL: https://github.com/guitdev/managey.git
